services:
  frontend:
    image: solomonlib/mern-frontend:latest
    ports:
      - "80:5173"
    networks:
      - mern

  backend:
    image: solomonlib/mern-backend:latest
    ports:
      - "5050:5050"
    networks:
      - mern
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db 
    networks:
      - mern

networks:
  mern:
    driver: bridge

volumes:
  mongo-data:
    driver: local

